### ISSUE TITLE
[bug] federation allowList does not seem to work

### ISSUE THREAD

**Issue by thomasdouwes** [SleeplessOne1917/lemmy-bot#10]
The allowList property of the federation option does not seem to be followed, and the bot will reply to all comments/posts on any federated community.
example:  
```
federation: {
  allowList: [
    {
      instance: 'lemmy.world',
      communities: ['vexillology']
    },
    {
      instance: 'lemmy.antemeridiem.xyz',
      communities: ['vexillologyjerk']
    }
  ]
},
```
I am using lemmy-bot 0.3.9 from npm

**Comment by thomasdouwes** [comment]
This might have been fixed by upgrading my lemmy instance from 0.17.2 to 0.17.4. it still replies to any local community but it seems to follow to allowList for federated communities

**Comment by thomasdouwes** [comment]
I have had no more issues since the lemmy update and some constant crashing has also been resolved. I think this was a problem with lemmy 0.17.2 and not this library. it still replies in all local communities however, is that intended?

**Comment by SleeplessOne1917** [comment]
It should not reply to all local communities. I will have to fix that.

**Comment by SleeplessOne1917** [comment]
Try using bot version 0.4.1 and see if it works now.

**Comment by thomasdouwes** [comment]
Sadly I can't upgrade my instance to 0.18.0, can I still test this version or would I need 0.18.0?

**Comment by SleeplessOne1917** [comment]
@thomasdouwes I *think* it should still work even if your instance is still one 0.17.x. The major difference between 0.17.x and 0.18.x is that the websocket API was removed. The bot uses the HTTP API now, but the HTTP API shouldn't have had any breaking changes between version.

**Comment by thomasdouwes** [comment]
I can't get the new version working on 0.17.4, I get `UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null` when starting the bot. However, I have quickly set up a new 0.18.1 test instance on my PC and the bot is no longer replying to all local communities. I can't get my test instance federating for some reason but I assume that is also working.
Even though I can't use the fix on my instance I'm going to close this issue because the bug is fixed. thanks for the fix.
