### ISSUE TITLE
Sometimes bot fails to start

### ISSUE THREAD

**Issue by kevinhikaruevans** [SleeplessOne1917/lemmy-bot#23]
Sometimes I'll start a script and it'll give me this error and exits. It'd be nice if it could gracefully handle this error.

I'm connecting to lemmy.world as my instance, which has weird connectivity issues. I'm wondering if the ws is timing out and `actorId` isn't getting set properly. If so, it would be nice if it could attempt to reconnect.

Log:

```
> ts-node src/main.ts

Connected to Lemmy Instance
Initializing DB
Logging in
Marking account as bot account
Subscribing to communities
/node_modules/lemmy-bot/dist/helpers.js:55
const extractInstanceFromActorId = (actorId) => actorId.match(/https?:\/\/(.*)\/(?:c|u)\/.*/)[1];
                                                                                             ^
TypeError: Cannot read properties of null (reading '1')
    at extractInstanceFromActorId (/node_modules/lemmy-bot/dist/helpers.js:55:94)
    at LemmyBot.<anonymous> (/node_modules/lemmy-bot/dist/bot.js:804:90)
    at Generator.next (<anonymous>)
    at /node_modules/lemmy-bot/dist/bot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/lemmy-bot/dist/bot.js:4:12)
    at WebSocketConnection.<anonymous> (/node_modules/lemmy-bot/dist/bot.js:449:51)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.emit (node:domain:489:12)
    at WebSocketConnection.processFrame (/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by SleeplessOne1917** [comment]
My actor ID regex might not have accounted for some edge case. Considering the logs say it's subscribing to communities, I take it that you're using an allow list?

**Comment by SleeplessOne1917** [comment]
My actor ID regex might not have accounted for some edge case. Considering the logs say it's subscribing to communities, I take it that you're using an allow list?

**Comment by kevinhikaruevans** [comment]
Yep, I'm using:

```
federation: {
    allowList: [
      {
        instance: 'lemmy.world',
        communities: ['news', 'world']
      },
      {
        instance: 'beehaw.org',
        communities: ['news']
      },
      {
        instance: 'lemmy.ml',
        communities: ['worldnews', 'news']
      }
    ]
  },
```

**Comment by SleeplessOne1917** [comment]
I think I know the issue. [Beehaw blocks lemmy.world](https://beehaw.org/post/567170). I'll have to put logic in for dealing with non federated instances.

**Comment by SleeplessOne1917** [comment]
I added a catch for getting community IDs in bot version 0.4.1. See if you still get the issue. You still won't be able to reach beehaw.org from a lemmy.world account, but your bot should at least not blow up this time.
