### ISSUE TITLE
Does not work on the new 0.18.0 update.

### ISSUE THREAD

**Issue by SigurdVie** [SleeplessOne1917/lemmy-bot#24]
Hey! I haven't gotten my bot to work after updating the instance to Lemmy 0.18.0. Is this because they no longer are using websockets? If so, will this library update?

**Comment by SleeplessOne1917** [comment]
I will update this library soon. Sorry for the inconvenience.

**Comment by Pdzly** [comment]
This wont work for 0.18.1 version
