### ISSUE TITLE
Unable to run bot due to issues with the examples

### ISSUE THREAD

**Issue by Hellhound1** [SleeplessOne1917/lemmy-bot#28]
Hi, wondering if you could help with where I'm going wrong.

I'm using the like me bot example, and getting the error "Expected 1 arguments, but got 2. (ts2554) on the Vote.Upvote lines and the same error on the SendPrivateMessage lines where the text is flagging the same error.

I'm really new to this so most likely an error with my setup but google has been no help in figuring this out.

Thanks

![image](https://github.com/SleeplessOne1917/lemmy-bot/assets/6584931/32d8bcdc-c21d-48c2-8646-56bb5d35958c)

edit: on Lemmy 0.18 and using bot version 0.4

**Comment by Pdzly** [comment]
Yeah it should be like

![grafik](https://github.com/SleeplessOne1917/lemmy-bot/assets/34943569/bcf0bd40-1d77-4e9b-b0d3-dc47707f46b9)

**Comment by SleeplessOne1917** [comment]
I'll have to check the demo code. I must not have updated it properly after the latest changes.

**Comment by SleeplessOne1917** [comment]
I updated the examples in the README. They should work now.
