### ISSUE TITLE
How to identify if a person is a mod in the community?

### ISSUE THREAD

**Issue by Pdzly** [SleeplessOne1917/lemmy-bot#29]
Is there a way to check if a person is a mod? In the "creator" variable there is just "admin" and this is not mod.

**Comment by SleeplessOne1917** [comment]
Currently no. You can get a list of mods for a community on a `GetCommunityResponse`, but I'll have to add a way to do that to the bot.

**Comment by SleeplessOne1917** [comment]
I added `isCommunityMod` to bot actions in version 0.4.1. This should make it easier to do what you're trying to do.
