### ISSUE TITLE
Spam of logging in and other stuff

### ISSUE THREAD

**Issue by Pdzly** [SleeplessOne1917/lemmy-bot#30]
![grafik](https://github.com/SleeplessOne1917/lemmy-bot/assets/34943569/9a2b55c7-0488-48e1-89db-744ac0a1dd4e)

The exception is there too but it was big data comming up. But the "Loggin in ..... Subscribing...." is annoying me and it spams the console at start

**Comment by Pdzly** [comment]
The database is locked is getting more and more of a annoyance.

**Comment by SleeplessOne1917** [comment]
Which version are you using? I used to get spam like that on version pre 0.4.0, but I haven't gotten it since I updated the library.

**Comment by Pdzly** [comment]
@SleeplessOne1917 it was pre 0.4.0 yeah but i cant even test it because lemmy.world has some incompatible version ( i guess ) aka 0.18.1-rc.4 as the lemmy-js-client has some issue too with it. Because of it i cant test it right now
