### ISSUE TITLE
0.18.1-rc.4 Is broke the bot totally

### ISSUE THREAD

**Issue by Pdzly** [SleeplessOne1917/lemmy-bot#31]
![grafik](https://github.com/SleeplessOne1917/lemmy-bot/assets/34943569/bc0ab7ca-eaeb-4f76-9bd8-dfa5b818460a)

The Code i used:
```TS
const bot = new LemmyBot({
(VALID CODE)
})

bot.start()
```

The lemmy version is 0.18.1-rc.4

**Comment by SleeplessOne1917** [comment]
Is the account of your bot an admin? The error you're getting is because it's trying to do something it needs to be an admin to do but it isn't an admin.

**Comment by Pdzly** [comment]
> Is the account of your bot an admin? The error you're getting is because it's trying to do something it needs to be an admin to do but it isn't an admin.

No it isnt but the only thing it is doing is starting. ( bot.start is the only thing ran )

**Comment by Pdzly** [comment]
*updated the issue to tell the lemmy version

**Comment by Pdzly** [comment]
Lmao yeah i found out its literally trying to do something admin only. I have to look into my code. Sry!

**Comment by Pdzly** [comment]
Its somewhere in the events... but i dont get it where ;( 

Are some events admin only too?

**Comment by Pdzly** [comment]
Ok i found out its the comment event. 
![grafik](https://github.com/SleeplessOne1917/lemmy-bot/assets/34943569/e4f45588-4ae0-4874-8e89-9c6d736d5691)

If i remove the comment event everything "works" but if i put the comment event in it throws in the error. 

The function doesnt even get called because the console.log doesnt get printed in the console.

**Comment by Pdzly** [comment]
Just a side note i get now rate_limit_error, but that is because i restarted the bot too many times. Because the edit profile is now strictly rate limited. and the bot edits the bots profile to be a bot. And that has a lower ratelimit

**Comment by Pdzly** [comment]
No it wasnt comment. wth.... you probably know what it was! Please let me know what event is admin only

**Comment by SleeplessOne1917** [comment]
@Pdzly there is a list of admin only bot actions in the README.

**Comment by Pdzly** [comment]
> @Pdzly there is a list of admin only bot actions in the README.

It wasnt a action it was just the event.
