### ISSUE TITLE
Getting `user_already_exists` error after login

### ISSUE THREAD

**Issue by fthues** [SleeplessOne1917/lemmy-bot#34]
Every login attempt results in a `user_already_exists` error. This probably happens in [saveUserSettings()](https://github.com/SleeplessOne1917/lemmy-bot/blob/d9716e4d48d432730d229271697758b2909af9d0/src/bot.ts#L1098) and looks like it's related to [this issue](https://github.com/LemmyNet/lemmy-js-client/issues/144), apparently one needs to include all user data in `saveUserSettings()`.

**Comment by SleeplessOne1917** [comment]
I'll make a fix, although it might make more sense to update the lemmy endpoint than the bot.

**Comment by fthues** [comment]
Agreed! 

How about adding a (temporary?) config option that when enabled would just skip the whole marking as a bot step, avoiding `saveUserSettings` altogether?

**Comment by sylverstream** [comment]
IMO it would be better if it would check if it was already marked as bot, and thus only call saveUserSettings when it's not marked as a bot yet? Saves a config setting :)

**Comment by Pdzly** [comment]
> Agreed!
> 
> How about adding a (temporary?) config option that when enabled would just skip the whole marking as a bot step, avoiding `saveUserSettings` altogether?

I am 100% for that as this is somewhat a possible ratelimit that could trip on too many times called ( for example script restarted )

**Comment by SleeplessOne1917** [comment]
I'll go with the config option. I would use @sylverstream's option if the login response included that information, but as it does not it would just add yet another request.

**Comment by SleeplessOne1917** [comment]
Added the config option in v0.4.3. Closing this issue.
