### ISSUE TITLE
First fetch works second not anymore

### ISSUE THREAD

**Issue by Pdzly** [SleeplessOne1917/lemmy-bot#36]
I created a bot and it didnt got any posts from my community. And after i debugged it. It fetches 1 time correctly but then it doesnt fetch it anymore.

```
  lemmyService.bot = new LemmyBot({
          instance: process.env.LEMMY_INSTANCE!,
          credentials: {
            username: process.env.LEMMY_USERNAME!,
            password: process.env.LEMMY_PW!,
          },
          connection: {
            minutesUntilReprocess: 1,
            secondsBetweenPolls: 30,
          },
          schedule: [],
          federation: "all",
          dbFile: "./lemmy.db",
          handlers: {
post: async ({
              botActions,
              postView,
              preventReprocess,
              reprocess,
            }) => {
        console.log("NEW POST")
                  });
```

It logs like in the initial start the first 30 posts and then i can wait like for 15 minutes nothing happens

**Comment by FireMasterK** [comment]
I see a similar behavior when testing this on my own lemmy instance:

<details>
<summary>Code:</summary>

```
const bot = new LemmyBot({
    instance: "feddit.rocks",
    credentials: {
        username: "PipedLinkBot",
        password: "REDACTED",
    },
    connection: {
        secondsBetweenPolls: 30,
    },
    federation: "all",
    dbFile: "db.sqlite3",
    handlers: {
        comment: ({
            commentView: {
                comment: { content, id },
            },
            botActions: { createComment },
        }) => {
            console.log(`Comment ${id} has content: ${content}`);
        },
        post: {
            handle: ({
                postView: {
                    post: { id, url, body },
                },
                botActions: { createComment },
            }) => {
                console.log(`Post ${id} has url: ${url}`);
                console.log(`Post ${id} has body: ${body}`);
            },
        },
        privateMessage: ({
            messageView: {
                private_message: { content, creator_id },
            },
            botActions: { sendPrivateMessage },
        }) => {
            console.log(`Message from ${creator_id} has content: ${content}`);
            sendPrivateMessage({
                recipient_id: creator_id,
                content: "Hello!",
            });
        },
    },
});

bot.start();
```
</details>

There are definitely federated comments/posts being made on my instance:
https://feddit.rocks/?dataType=Comment&listingType=All&page=1&sort=New
https://feddit.rocks/?dataType=Post&listingType=All&page=1&sort=New

**Comment by FireMasterK** [comment]
I fixed this by changing the `sort` to `New`.
```
        comment: {
            handle: ({
                commentView: {
                    comment: { content, id },
                },
                botActions: { createComment },
            }) => {
                console.log(`Comment ${id} has content: ${content}`);
            },
            sort: "New",
        },
        post: {
            handle: ({
                postView: {
                    post: { id, url, body },
                },
                botActions: { createComment },
            }) => {
                console.log(`Post ${id} has url: ${url}`);
                console.log(`Post ${id} has body: ${body}`);
            },
            sort: "New",
        },
```

**Comment by SleeplessOne1917** [comment]
> I fixed this by changing the sort to New.

What was it set to before? The default?

**Comment by Pdzly** [comment]
> > I fixed this by changing the sort to New.
> 
> What was it set to before? The default?

Yeah default

**Comment by Pdzly** [comment]
> I fixed this by changing the `sort` to `New`.
> 
> ```
>         comment: {
>             handle: ({
>                 commentView: {
>                     comment: { content, id },
>                 },
>                 botActions: { createComment },
>             }) => {
>                 console.log(`Comment ${id} has content: ${content}`);
>             },
>             sort: "New",
>         },
>         post: {
>             handle: ({
>                 postView: {
>                     post: { id, url, body },
>                 },
>                 botActions: { createComment },
>             }) => {
>                 console.log(`Post ${id} has url: ${url}`);
>                 console.log(`Post ${id} has body: ${body}`);
>             },
>             sort: "New",
>         },
> ```

It is still not even getting my test comments after waiting for 15 mins. But new comments are getting send.

**Comment by Pdzly** [comment]
Ok with the sort options it is somewhat acceptable and i think currently only reliable way.
