### ISSUE TITLE
Detect if Post URL / Image / Title / Body changed?

### ISSUE THREAD

**Issue by rcmaehl** [SleeplessOne1917/lemmy-bot#47]
I was wondering if Lemmy has any native ability to detect if a post was changed, and what was changed without having to store that information in an external database? If so, does lemmy-bot also have that functionality?

**Comment by Pdzly** [comment]
Not natively but you can implement it with the timed executions.

**Comment by SleeplessOne1917** [comment]
I second @Pdzly's recommendation.

**Comment by SleeplessOne1917** [comment]
Closing because workaround was suggested and the API doesn't support a better way at the moment.
